Сверстал header для главной страницы
htmlacademy-htmlcss/1596691-technomart-29 pull request #2
Opened 2020-09-15 14:03 UTC by alexrocks4

Прошу проверить верстку для хедера главной страницы.

2020-09-16 19:37 UTC, mkolotovich requested changes

2020-09-16 19:37 UTC, mkolotovich commented on index.html
> +      <p>
Этот параграф лишний удаляй его. Не засоряй преждевременно html код лишними тегами, добавляй их по мере необходимости.

2020-09-16 19:37 UTC, mkolotovich commented on index.html
> +        <a href="index.html">ТЕХНОМАРТ</a>
Логотипы делаются с помощью изображения, даже если он состоит из текста. Удали текст внутри ссылки и вставь туда заглушку картинки.

2020-09-16 19:37 UTC, mkolotovich commented on index.html
> +          <i></i>
Я думаю, что использовать здесь тег `<i> `для иконки это не лучшее решение. Тег` <i> `обычно используют для иконок в иконочных шрифтах. Здесь же обычный свг. Так, что используй здесь свг тег.

2020-09-16 19:37 UTC, mkolotovich commented on index.html
> +        <input type="text" id="search-form-search-string" name="search-string">
Задай атрибут placrholder со значением Поиск:

2020-09-16 19:37 UTC, mkolotovich commented on index.html
> +      <p>
Опять же. Лишний тег. Удаляй.

2020-09-16 19:37 UTC, mkolotovich commented on index.html
> +          <i></i> Закладки: 0
Тоже самое. Используй свг вместо i

2020-09-16 19:37 UTC, mkolotovich commented on index.html
> +          <i></i> Корзина: 0
Делай по аналогии, как я написал выше.

2020-09-16 19:37 UTC, mkolotovich commented on index.html
> +        <i>Интернет магазин<br>
Удаляй br. Перенос сделаем с помощью стилей. Используй br только в тех местах, где невозможно сделать перенос как на макете с помощью стилей.

2020-09-16 19:37 UTC, mkolotovich commented on index.html
> +        <span>г.Санкт-Петербург, ул. Б.Конюшенная, д.19/8</span>
Как делать иконки я писал выше, а номер телефона согласно критерию Д29 - Телефоны размечены ссылками с протоколом tel (https://up.htmlacademy.ru/htmlcss/29/criteries#d29)

2020-09-16 19:37 UTC, mkolotovich commented on index.html
> +          <i></i> Войти
Делай как писал выше.

2020-09-16 19:37 UTC, mkolotovich commented on index.html
> +          <i></i> Регистрация
На макете нет иконки для Регистрации и удаляй лишний параграф

2020-09-16 19:37 UTC, mkolotovich commented on index.html
> +            <a href="index.html">Главная</a>
Страница ссылается сама на себя. Это не есть хорошо. Оставь здесь заглушку как делал для других ссылок.

2020-09-16 19:47 UTC, mkolotovich requested changes
Исправь замечания

2020-09-16 19:47 UTC, mkolotovich commented on index.html
> +      <h1>Интернет-магазин Техномарт</h1>
Этого заголовка нет макете. Для таких заголовков используй класс visually hidden

2020-09-16 19:47 UTC, mkolotovich commented on index.html
> +        <h2>Товары и услуги</h2>
Тоже самое используй класс visually hidden

2020-09-16 19:47 UTC, mkolotovich commented on index.html
> +        </section>
Вот это лучше разметить через список. Иконки делай через тег свг

2020-09-16 19:47 UTC, mkolotovich commented on index.html
> +          <img src="https://via.placeholder.com/620x266" width="620" height="266" alt="Перфораторы!">
Ты пропустил в разметке кнопки переключения слайдов находящиеся внизу слайдов. Изображения слайдов это не контентные, а фоновые изображения. Их мы вставим с помощью стилей.

2020-09-16 20:41 UTC, mkolotovich requested changes
Исправь замечания

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +        <p>КОМПАНИЯ «Техномарт»</p>
Я думаю, что это заголовок. Если ты так не считаешь, то задай h2 класс visually hidden

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +           ремонта и строительства не оставит равнодушными любителей сэкономить на<br>
Удаляй эти br. Перенос сделаем через стили.

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +          Мы можем доставить ваш товар в самые отдаленные точки России!<br>
Удаляй br. Перенос сделаем через стили.

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +        <p>Вы можете забрать товар сами,<br>
Удаляй br. Перенос сделаем через стили.

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +          <a href="">Каталог</a>
Добавь здесь ссылку на страницу каталога, как в шапке

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +        <h2>Как с нами свзяаться</h2>
Тут опечатка, а также задай класс visually hidden

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +          +7 (812) 555-05-55
телефон разметь через ссылку, как в шапке

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +        <p>г. Санкт-Петербург, ул. Б. Конюшенная, д. 19/8<br>
Удаляй br. Перенос сделаем через стили.

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +          Обратная связь:<br>
Удаляй br. Перенос сделаем через стили.

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +        <h2>Мы в соцсетях</h2>
задай h2 класс visually hidden

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +        </p>
Перенеси этот параграф после соц.сетей, чтобы был порядок элементов как на макете

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +        <h2>Защита авторских прав</h2>
задай h2 класс visually hidden

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +        </p>
этот параграф вынеси отсюда и перенеси его перед соц.сетями.

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +          © 2010–2019 Компания «Техномарт»<br>
Удаляй br. Перенос сделаем через стили.

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +          Разработано — <br>
Удаляй br. Перенос сделаем через стили.

2020-09-16 20:41 UTC, mkolotovich commented on index.html
> +          <a href="https://htmlacademy.ru">htmlacademy.ru</a>
Согласно ТЗ 3.5. Ссылка в подвале htmlacademy.ru ведёт на лендинг интенсива «HTML и CSS. Профессиональная вёрстка сайтов» (https://up.htmlacademy.ru/htmlcss/29/project/technomart#technomart-3-5)

2020-09-21 08:36 UTC, mkolotovich commented on index.html
> +        <i>Интернет Интернет-магазин
Убери слово Интернет, оно у тебя дублируется

2020-09-21 08:36 UTC, mkolotovich commented on index.html
> +            <a href="index.html">Главная</a>
Я пересмотрел критерии акселератора. Это касается логотипа на главной - 11. **Логотип** является картинкой. (Логотип обернут в ссылку, по умолчанию ссылка ведет на главную страницу, на главной странице ссылка без href)(https://www.notion.so/1-78b0103e8fbb48fc81fccf21795dd3c5)

2020-09-21 08:54 UTC, mkolotovich requested changes
Исправь два замечания и мердж

2020-09-21 08:54 UTC, mkolotovich commented on index.html
> +           <button type="button" hidden></button>
Зачем кнопки прятать и отображать только при работоспособности JS? Слайдер можно сделать и на CSS. Убери у кнопок атрибут hidden, а кнопки переключения я тебе уже говорил, что нужно разметить не через button, а через input type="radio"

2020-09-21 09:36 UTC, alexrocks4 commented on index.html
> +           <button type="button" hidden></button>
Ок. 
hidden решил  сделать для прогрессивного улучшения. Если не будет работать ни CSS ни JS, то эти кнопки работать не будут и их можно спрятать.

2020-09-21 11:06 UTC, mkolotovich commented on index.html
> +          <input type="radio">
добавь атрибут name с одинаковым значением

2020-09-21 11:10 UTC, mkolotovich reviewed
Исправь в следующем задании

2020-09-21 11:10 UTC, merged