Сделал базовую стилизацию header на Главной
htmlacademy-htmlcss/1596691-technomart-29 pull request #6
Opened 2020-09-25 09:09 UTC by alexrocks4

2020-09-25 10:22 UTC, mkolotovich requested changes
Я бы всё-таки предложил бы тебе в секции Товары и услуги в списке, внутри элемента списка делать секции с заголовками. Либо на крайняк оборачивать название элементов списка например в b или strong, а метку New наоборот вместо b обернуть в span. Потому, что если оставить как есть сейчас, то это не удобно стилизовать. Доделывай базовую стилизацию главной страницы и отправляй задание на проверку

2020-09-25 10:22 UTC, mkolotovich commented on css/style.css
> +
Создай селектор main > section:nth-child(2) > ul > li b и задай ему font-weight: normal;font-size: 14px;line-height: 18px;text-transform: uppercase;color: #FFFFFF;

2020-09-28 14:43 UTC, mkolotovich requested changes

2020-09-28 14:43 UTC, mkolotovich commented on css/style.css
> +    font-weight: 700;
Задай text-transform: uppercase;

2020-09-28 14:52 UTC, mkolotovich requested changes

2020-09-28 14:52 UTC, mkolotovich commented on css/style.css
> +    background-color: var(--basic-red);
Задай font-weight: normal;

2020-09-28 14:52 UTC, mkolotovich commented on css/style.css
> +    color: var(--basic-dark-extra);
Измени на #32425C

2020-09-29 07:32 UTC, mkolotovich requested changes
Исправь одно замечание с первой проверки плюс новые.

2020-09-29 07:32 UTC, mkolotovich commented on css/style.css
> +
Создай селектор .search-form-input:focus::placeholder и задай ему {
    color:black
}

2020-09-29 07:32 UTC, mkolotovich commented on css/style.css
> +    text-decoration: underline;
Убери это свойство. Оно лишнее.

2020-09-29 16:55 UTC, alexrocks4 commented on css/style.css
> +    text-decoration: underline;
Да, ошибся. Но тогда, наверное, нужно здесь text-decoration: none. Иначе при клике подчеркивание не убирается.
Переделал на text-decoration: none

2020-09-30 06:25 UTC, mkolotovich commented on css/style.css
> +    text-decoration: underline;
Почему не убирается? Как раз при клике убирается. Изначально при ховере есть подчеркивание, но когда кликаешь подчеркивание проподает, так что можешь удалить text-decoration: none, оно избыточно.

2020-09-30 06:26 UTC, merged